name: Auto Tag from pyproject.toml

on:
  push:
    branches:
      - main  # or whichever branch you want to tag from

jobs:
  tag-from-pyproject:
    runs-on: ubuntu-latest
    steps:
      # 1. Check out the repo
      - name: Check out repository
        uses: actions/checkout@v3

      # 2. Set up Python 3.11 (has tomllib built in)
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      # 3. Parse version from pyproject.toml
      - name: Extract version
        id: version
        run: |
          # We read the version via a one-liner. 
          # If your pyproject.toml has no [project].version, this fails.
          version=$(python -c "import tomllib; data=tomllib.load(open('pyproject.toml','rb')); print(data['project']['version'])")
          echo "Found version: $version"
          
          # Save 'version' for use in subsequent steps
          echo "version=$version" >> $GITHUB_OUTPUT

      # 4. Create and push the tag if missing
      - name: Create and push tag if needed
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          VERSION="${{ steps.version.outputs.version }}"
          echo "Discovered version: $VERSION"

          if [ -z "$VERSION" ]; then
            echo "No version found in pyproject.toml!"
            exit 1
          fi

          # Check if the tag already exists
          if git rev-parse "v$VERSION" >/dev/null 2>&1; then
            echo "Tag v$VERSION already exists. Doing nothing."
          else
            echo "Creating and pushing tag v$VERSION..."
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git tag "v$VERSION"
            git push origin "v$VERSION"
            echo "Pushed tag v$VERSION."
          fi